services:
  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin
    ports:
      - 50000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - "./pgadmin/data:/var/lib/pgadmin"
      - "./pgadmin/servers.json:/pgadmin4/servers.json"
  
  postgresql:
    image: postgis/postgis:17-3.5-alpine
    container_name: postgresql
    ports:
      - 55432:5432
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - "./postgresql/init:/docker-entrypoint-initdb.d"
      - "postgresql:/var/lib/postgresql/data"
        
volumes:
  postgresql:
    external: false